/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const MushroomGuideLazyImport = createFileRoute('/mushroom-guide')()

// Create/Update Routes

const MushroomGuideLazyRoute = MushroomGuideLazyImport.update({
  id: '/mushroom-guide',
  path: '/mushroom-guide',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/mushroom-guide.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/mushroom-guide': {
      id: '/mushroom-guide'
      path: '/mushroom-guide'
      fullPath: '/mushroom-guide'
      preLoaderRoute: typeof MushroomGuideLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mushroom-guide': typeof MushroomGuideLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mushroom-guide': typeof MushroomGuideLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/mushroom-guide': typeof MushroomGuideLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mushroom-guide'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mushroom-guide'
  id: '__root__' | '/' | '/mushroom-guide'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MushroomGuideLazyRoute: typeof MushroomGuideLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MushroomGuideLazyRoute: MushroomGuideLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/mushroom-guide"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/mushroom-guide": {
      "filePath": "mushroom-guide.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
